package com.tranphucvinh.constant;

import lombok.Getter;

public enum FirebaseNotificationEnum {
    KR_LANG("ko"),
    MM_LANG("my"),
    EN_LANG("en"),
    NOTIFICATION_PURPOSE("{purpose}"),
    EMBASSY_PURPOSE("EMBASSY_PURPOSE"),
    DEFAULT_PURPOSE("passport"),
    SIGNUP_NOTIFICATION_KR_CONTENT("회원가입 완료! 회원이 되신 것을 환영합니다."),
    SIGNUP_NOTIFICATION_EN_CONTENT("Membership Completed! Welcome to become a member."),
    SIGNUP_NOTIFICATION_MM_CONTENT("အသင်းဝင်မှတ်ပုံတင်ခြင်း ပြီးပါပြီ။ အဖွဲ့ဝင်ဖြစ်ခြင်းမှကြိုဆိုပါတယ်။"),
    CHANGE_PASSWORD_KR_CONTENT("비밀번호가 변경되었습니다."),
    CHANGE_PASSWORD_EN_CONTENT("Your password has been changed."),
    CHANGE_PASSWORD_MM_CONTENT("သင့်စကားဝှက်ကို ပြောင်းလိုက်ပါပြီ။"),
    CREATE_EMBASSY_REGISTRATION_KR_CONTENT("대사관 방문 신청 {purpose} 이 완료되었습니다."),
    CREATE_EMBASSY_REGISTRATION_EN_CONTENT("Your embassy visit application {purpose} has been completed."),
    CREATE_EMBASSY_REGISTRATION_MM_CONTENT("သံရုံးလည်ပတ်မှုလျှောက်လွှာ {purpose} ပြီးသွားပါပြီ။"),
    CANCEL_EMBASSY_REGISTRATION_KR_CONTENT("대사관 방문 신청 ({purpose}) 취소가 완료되었습니다."),
    CANCEL_EMBASSY_REGISTRATION_EN_CONTENT("Cancellation of the embassy visit application ({purpose}) has been completed."),
    CANCEL_EMBASSY_REGISTRATION_MM_CONTENT("သံရုံးလည်ပတ်ခွင့်လျှောက်လွှာ ({purpose}) ကို ပယ်ဖျက်ပြီးပါပြီ။"),
    COMPLETE_EMBASSY_REGISTRATION_KR_CONTENT("대사관 방문 ({purpose}) 이 완료 처리되었습니다."),
    COMPLETE_EMBASSY_REGISTRATION_EN_CONTENT("Your embassy visit ({purpose}) has been completed."),
    COMPLETE_EMBASSY_REGISTRATION_MM_CONTENT("မင်းရဲ့သံရုံးလည်ပတ်မှုရဲ့ ({purpose}) ပြီးသွားပါပြီ။"),
    UNVISIT_EMBASSY_REGISTRATION_KR_CONTENT("대사관 방문 ({purpose}) 이 미방문 처리되었습니다."),
    UNVISIT_EMBASSY_REGISTRATION_EN_CONTENT("Your visit to the embassy ({purpose}) has not been processed."),
    UNVISIT_EMBASSY_REGISTRATION_MM_CONTENT("သံရုံး ဘွတ်ကင်ယူခြင်း ({purpose})ကို ပျက်ကွက်အဖြစ် ပြောင်းလဲလိုက်ပါပြီ။"),
    CREATE_ADVISORY_KR_CONTENT("게시글이 등록되었습니다."),
    CREATE_ADVISORY_EN_CONTENT("Your post has been registered."),
    CREATE_ADVISORY_MM_CONTENT("ပို့စ်ကို စာရင်းသွင်းပြီးပါပြီ။"),
    ANSWER_ADVISORY_KR_CONTENT("내가 작성한 게시글에 답변이 달렸습니다."),
    ANSWER_ADVISORY_EN_CONTENT("The post I wrote was answered."),
    ANSWER_ADVISORY_MM_CONTENT("ကျွန်တော်ရေးတဲ့ ပို့စ်ကို အကြောင်းပြန်ခဲ့ပါတယ်။"),
    COMMENT_ADVISORY_KR_CONTENT("내가 작성한 게시글에 댓글이 달렸습니다."),
    COMMENT_ADVISORY_EN_CONTENT("A comment came up on the post I wrote."),
    COMMENT_ADVISORY_MM_CONTENT("ကျွန်တော်ရေးတဲ့ post မှာ comment တစ်ခုရှိတယ်။"),
    CREATE_NOTIFICATION_KR_CONTENT("새로운 공지사항이 있습니다."),
    CREATE_NOTIFICATION_EN_CONTENT("We have a new notice."),
    CREATE_NOTIFICATION_MM_CONTENT("ကြေငြာချက်အသစ်တစ်ခုရှိပါတယ်။"),
    COMMON_KR_TITLE(""),
    COMMON_EN_TITLE(""),
    COMMON_MM_TITLE(""),
    ALARM_REF_TABLE_ACCOUNT("tb_account"),
    ALARM_REF_TABLE_MEMBER("tb_member"),
    ALARM_REF_TABLE_ADVISORY("tb_advisory"),
    ALARM_REF_TABLE_ADVISORY_ANSWER("tb_advisory_answer"),
    ALARM_REF_TABLE_ADVISORY_COMMENT("tb_advisory_comment"),
    ALARM_REF_TABLE_SCHEDULE("tb_member"),
    ALARM_REF_TABLE_EMBASSY("tb_embassy_registration"),
    ALARM_REF_TABLE_NOTIFICATION("tb_notification"),
    ALARM_REF_TABLE_ALARM("tb_alarm"),
    FOREIGN_REGISTRAION_EXPIRED_CONTENT_EN("[Foreigner Registration] Your stay will expire in {SCHEDULE_DAY}. (Expiration date {EXPIRED_DATE})"),
    FOREIGN_REGISTRAION_EXPIRED_CONTENT_KR("[외국인 등록] 체류 기간이 {SCHEDULE_DAY}일 뒤 만료됩니다. (만료일 {EXPIRED_DATE})"),
    FOREIGN_REGISTRAION_EXPIRED_CONTENT_MM("[ID ကဒ် ] သက်တမ်းကတော့ {SCHEDULE_DAY} ရက်ကြာလျှင် သက်တမ်းကုန်ဆုံးပါမည်။ (ကုန်ဆုံးရက် {EXPIRED_DATE})"),
    FOREIGN_REGISTRAION_EXPIRED_TITLE_EN("FOREIGN_REGISTRATION_TITLE_EN"),
    FOREIGN_REGISTRAION_EXPIRED_TITLE_KR("FOREIGN_REGISTRATION_TITLE_KR"),
    FOREIGN_REGISTRAION_EXPIRED_TITLE_MM("FOREIGN_REGISTRATION_TITLE_MM"),
    VISA_EXPIRED_CONTENT_EN("[Visa] Expires in {SCHEDULE_DAY}. (Expiration date {EXPIRED_DATE})"),
    VISA_EXPIRED_CONTENT_KR("[비자] {SCHEDULE_DAY}일 뒤 만료됩니다. (만료일 {EXPIRED_DATE})"),
    VISA_EXPIRED_CONTENT_MM("[ဗီဇာ] {SCHEDULE_DAY} ရက်ကြာလျှင် သက်တမ်းကုန်ဆုံးပါမည်။ (ကုန်ဆုံးရက် {EXPIRED_DATE})"),
    VISA_EXPIRED_TITLE_EN("VISA_TITLE_EN"),
    VISA_EXPIRED_TITLE_KR("VISA_TITLE_KR"),
    VISA_EXPIRED_TITLE_MM("VISA_TITLE_MM"),
    PASSPORT_EXPIRED_CONTENT_EN("[Passport] Expires in {SCHEDULE_DAY}. (Expiration date {EXPIRED_DATE})"),
    PASSPORT_EXPIRED_CONTENT_KR("[여권] {SCHEDULE_DAY}일 뒤 만료됩니다. (만료일 {EXPIRED_DATE})"),
    PASSPORT_EXPIRED_CONTENT_MM("[နိုင်ငံကူးလက်မှတ်] {SCHEDULE_DAY} ရက်ကြာလျှင် သက်တမ်းကုန်ဆုံးပါမည်။ (ကုန်ဆုံးရက် {EXPIRED_DATE})"),
    PASSPORT_EXPIRED_TITLE_EN("PASSPORT_TITLE_EN"),
    PASSPORT_EXPIRED_TITLE_KR("PASSPORT_TITLE_KR"),
    PASSPORT_EXPIRED_TITLE_MM("PASSPORT_TITLE_MM"),
    CERTIFICATION_EXPIRED_CONTENT_EN("[Certificate] Expires in {CERTIFICATION_NAME} {SCHEDULE_DAY} (Expiration Date {EXPIRED_DATE})"),
    CERTIFICATION_EXPIRED_CONTENT_KR("[인증] {CERTIFICATION_NAME} {SCHEDULE_DAY}일 뒤 만료됩니다. (만료일 {EXPIRED_DATE})"),
    CERTIFICATION_EXPIRED_CONTENT_MM("[ထောက်ခံစာ] {CERTIFICATION_NAME} {SCHEDULE_DAY} ရက်ကြာလျှင် သက်တမ်းကုန်ဆုံးပါမည်။ (ကုန်ဆုံးရက် {EXPIRED_DATE})"),
    CERTIFICATION_EXPIRED_TITLE_EN("CERTIFICATION_TITLE_EN"),
    CERTIFICATION_EXPIRED_TITLE_KR("CERTIFICATION_TITLE_KR"),
    CERTIFICATION_EXPIRED_TITLE_MM("CERTIFICATION_TITLE_MM"),
    EMBASSY_REGISTRATION_EXPIRED_CONTENT_EN("It is {SCHEDULE_DAY} days before the embassy visit."),
    EMBASSY_REGISTRATION_EXPIRED_CONTENT_KR("대사관 방문 {SCHEDULE_DAY}일전 입니다."),
    EMBASSY_REGISTRATION_EXPIRED_CONTENT_MM("သံရုံး ဘွတ်ကင်ရက် မရောက်ခင် {SCHEDULE_DAY} ရက်သာ လိုပါတော့သည်။"),
    EMBASSY_REGISTRATION_EXPIRED_TITLE_EN("CERTIFICATION_TITLE_EN"),
    EMBASSY_REGISTRATION_EXPIRED_TITLE_KR("CERTIFICATION_TITLE_KR"),
    EMBASSY_REGISTRATION_EXPIRED_TITLE_MM("CERTIFICATION_TITLE_MM"),
    SCHEDULE_DAY("{SCHEDULE_DAY}"),
    EXPIRED_DATE("{EXPIRED_DATE}"),
    CERTIFICATION_NAME("{CERTIFICATION_NAME}"),
    CHANGE_EMBASSY_REGISTRATION_EN_CONTENT("The schedule for your Embassy visit ({purpose}) has been changed."),
    CHANGE_EMBASSY_REGISTRATION_KR_CONTENT("대사관 방문 신청 ({purpose}) 일정이 변경 되었습니다."),
    CHANGE_EMBASSY_REGISTRATION_MY_CONTENT("သံရုံးလည်ပတ်မှုလျှောက်လွှာ ({purpose}) အချိန်ဇယားကို ပြောင်းလဲလိုက်ပါပြီ။"),
    EMBASSY_REGISTRATION_CANCELED_AS_EMBASSY_NOT_OPEN_EN_CONTENT("The visit was canceled as the embassy was not open during this period."),
    EMBASSY_REGISTRATION_CANCELED_AS_EMBASSY_NOT_OPEN_KR_CONTENT("이 기간 동안 대사관이 문을 열지 않아 방문 일정이 취소되었습니다."),
    EMBASSY_REGISTRATION_CANCELED_AS_EMBASSY_NOT_OPEN_MM_CONTENT("ဤကာလအတွင်း သံရုံး မဖွင့်လှစ်သောကြောင့် ဘိုကင်ရက်ချိန်းကို ဖျက်သိမ်းလိုက်ပါသည်။"),
    ;

    FirebaseNotificationEnum(String message) {
        this.message = message;
    }

    @Getter
    private String message;
}
